class AuthenticationError(Exception):
    """Exceção lançada quando há erro na autenticação"""

    pass
